[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
humanize-bytes = "1.0.6"
rustc-hash = "2"
roaring = { version = "0.10.6", features = [] }
thousands = "0.2.0"
croaring = "2.0.3"
